### ISSUE TITLE
n1-install或者n1-install 0都不能完全格式化EMMC（表现为install后docker的数据依然存在）

### ISSUE THREAD

**Issue by yubanmeiqin9048** [tuanqing/install-program#5]

**Comment by tuanqing** [comment]
你说的这种情况是由于 `dockerd` 进程占用 `/opt` 导致，这将导致挂载在 `/opt` 上的分区无法卸载。
最新版会在安装或更新的时候先杀掉 `dokerd` ，理论上你说的情况应该不会出现。

**Comment by yubanmeiqin9048** [comment]
> 你说的这种情况是由于 `dockerd` 进程占用 `/opt` 导致，这将导致挂载在 `/opt` 上的分区无法卸载。
> 最新版会在安装或更新的时候先杀掉 `dokerd` ，理论上你说的情况应该不会出现。

root@OpenWrt:~# n1-install
emmc: /dev/mmcblk1
usb:  /dev/sda

backup u-boot...
create mbr and partition...
restore u-boot...
format boot partiton...
format root partiton...
format data partiton...
mkdir: can't create directory '/install/': No space left on device
mkdir: can't create directory '/install/': No space left on device
mount: /install/boot: mount point does not exist.
copy bootable file...
cp: can't create '/install/boot/System.map-5.4.83-flippy-50+o': No such file or directory
cp: can't create '/install/boot/aml_autoscript': No such file or directory
cp: can't create '/install/boot/aml_autoscript.cmd': No such file or directory
cp: can't create '/install/boot/armbian_first_run.txt.template': No such file or directory
cp: can't create '/install/boot/boot-emmc.cmd': No such file or directory
cp: can't create '/install/boot/boot-emmc.ini': No such file or directory
cp: can't create '/install/boot/boot-emmc.scr': No such file or directory
cp: can't create '/install/boot/boot.bmp': No such file or directory
cp: can't create '/install/boot/boot.cmd': No such file or directory
cp: can't create '/install/boot/boot.ini': No such file or directory
cp: can't create '/install/boot/boot.scr': No such file or directory
cp: can't create '/install/boot/config-5.4.83-flippy-50+o': No such file or directory
cp: can't create directory '/install/boot/dtb': No such file or directory
cp: can't create '/install/boot/emmc_autoscript': No such file or directory
cp: can't create '/install/boot/emmc_autoscript.cmd': No such file or directory
cp: can't create '/install/boot/initrd.img-5.4.83-flippy-50+o': No such file or directory
cp: can't create '/install/boot/s905_autoscript': No such file or directory
cp: can't create '/install/boot/s905_autoscript.cmd': No such file or directory
cp: can't create '/install/boot/u-boot.sd': No such file or directory
cp: can't create '/install/boot/u-boot.usb': No such file or directory
cp: can't create '/install/boot/uEnv.txt': No such file or directory
cp: can't create '/install/boot/uInitrd': No such file or directory
cp: can't create '/install/boot/zImage': No such file or directory
edit uEnv...
sed: /install/boot/uEnv.txt: No such file or directory
mv: can't rename '/install/boot/boot-emmc.scr': No such file or directory
umount: /dev/mmcblk1p1: not mounted.
mount: /install/root: mount point does not exist.
copy rootfs...
 --> copy bin...
cp: can't create directory '/install/root': No such file or directory
 --> copy etc...
cp: can't create directory '/install/root': No such file or directory
 --> copy lib...
cp: can't create directory '/install/root': No such file or directory
 --> copy root...
cp: can't create directory '/install/root': No such file or directory
 --> copy sbin...
cp: can't create directory '/install/root': No such file or directory
 --> copy usr...
cp: can't create directory '/install/root': No such file or directory
 --> copy www...
cp: can't create directory '/install/root': No such file or directory
/usr/bin/n1-install: cd: line 111: can't cd to /install/root: No such file or directory
mkdir: can't create directory 'boot': File exists
mkdir: can't create directory 'dev': File exists
mkdir: can't create directory 'mnt': File exists
mkdir: can't create directory 'opt': File exists
mkdir: can't create directory 'overlay': File exists
mkdir: can't create directory 'proc': File exists
mkdir: can't create directory 'rom': File exists
mkdir: can't create directory 'run': File exists
mkdir: can't create directory 'sys': File exists
mkdir: can't create directory 'tmp': File exists
 --> link lib64...
 --> link var...
ln: var/tmp: File exists
edit fstab...
sync...
umount: /dev/mmcblk1p2: not mounted.
copy openwrt os to emmc done!

**Comment by yubanmeiqin9048** [comment]
> 你说的这种情况是由于 `dockerd` 进程占用 `/opt` 导致，这将导致挂载在 `/opt` 上的分区无法卸载。
> 最新版会在安装或更新的时候先杀掉 `dokerd` ，理论上你说的情况应该不会出现。

上面这个情况有时候会出现，还有一个一直存在的问题是：使用mknop构建的N1固件在添加wan口（作单臂路由使用）后LUCI页面的在线用户数显示异常（一直显示为零）

**Comment by tuanqing** [comment]
> > 你说的这种情况是由于 `dockerd` 进程占用 `/opt` 导致，这将导致挂载在 `/opt` 上的分区无法卸载。
> > 最新版会在安装或更新的时候先杀掉 `dokerd` ，理论上你说的情况应该不会出现。
> 
> root@OpenWrt:~# n1-install
> emmc: /dev/mmcblk1
> usb: /dev/sda
> 
> backup u-boot...
> create mbr and partition...
> restore u-boot...
> format boot partiton...
> format root partiton...
> format data partiton...
> mkdir: can't create directory '/install/': No space left on device
> mkdir: can't create directory '/install/': No space left on device
> mount: /install/boot: mount point does not exist.
> copy bootable file...
> cp: can't create '/install/boot/System.map-5.4.83-flippy-50+o': No such file or directory
> cp: can't create '/install/boot/aml_autoscript': No such file or directory
> cp: can't create '/install/boot/aml_autoscript.cmd': No such file or directory
> cp: can't create '/install/boot/armbian_first_run.txt.template': No such file or directory
> cp: can't create '/install/boot/boot-emmc.cmd': No such file or directory
> cp: can't create '/install/boot/boot-emmc.ini': No such file or directory
> cp: can't create '/install/boot/boot-emmc.scr': No such file or directory
> cp: can't create '/install/boot/boot.bmp': No such file or directory
> cp: can't create '/install/boot/boot.cmd': No such file or directory
> cp: can't create '/install/boot/boot.ini': No such file or directory
> cp: can't create '/install/boot/boot.scr': No such file or directory
> cp: can't create '/install/boot/config-5.4.83-flippy-50+o': No such file or directory
> cp: can't create directory '/install/boot/dtb': No such file or directory
> cp: can't create '/install/boot/emmc_autoscript': No such file or directory
> cp: can't create '/install/boot/emmc_autoscript.cmd': No such file or directory
> cp: can't create '/install/boot/initrd.img-5.4.83-flippy-50+o': No such file or directory
> cp: can't create '/install/boot/s905_autoscript': No such file or directory
> cp: can't create '/install/boot/s905_autoscript.cmd': No such file or directory
> cp: can't create '/install/boot/u-boot.sd': No such file or directory
> cp: can't create '/install/boot/u-boot.usb': No such file or directory
> cp: can't create '/install/boot/uEnv.txt': No such file or directory
> cp: can't create '/install/boot/uInitrd': No such file or directory
> cp: can't create '/install/boot/zImage': No such file or directory
> edit uEnv...
> sed: /install/boot/uEnv.txt: No such file or directory
> mv: can't rename '/install/boot/boot-emmc.scr': No such file or directory
> umount: /dev/mmcblk1p1: not mounted.
> mount: /install/root: mount point does not exist.
> copy rootfs...
> --> copy bin...
> cp: can't create directory '/install/root': No such file or directory
> --> copy etc...
> cp: can't create directory '/install/root': No such file or directory
> --> copy lib...
> cp: can't create directory '/install/root': No such file or directory
> --> copy root...
> cp: can't create directory '/install/root': No such file or directory
> --> copy sbin...
> cp: can't create directory '/install/root': No such file or directory
> --> copy usr...
> cp: can't create directory '/install/root': No such file or directory
> --> copy [www](http://www)...
> cp: can't create directory '/install/root': No such file or directory
> /usr/bin/n1-install: cd: line 111: can't cd to /install/root: No such file or directory
> mkdir: can't create directory 'boot': File exists
> mkdir: can't create directory 'dev': File exists
> mkdir: can't create directory 'mnt': File exists
> mkdir: can't create directory 'opt': File exists
> mkdir: can't create directory 'overlay': File exists
> mkdir: can't create directory 'proc': File exists
> mkdir: can't create directory 'rom': File exists
> mkdir: can't create directory 'run': File exists
> mkdir: can't create directory 'sys': File exists
> mkdir: can't create directory 'tmp': File exists
> --> link lib64...
> --> link var...
> ln: var/tmp: File exists
> edit fstab...
> sync...
> umount: /dev/mmcblk1p2: not mounted.
> copy openwrt os to emmc done!

`root` 分区空间不足
